class PageLayout:
    DPI = 300

    WIDTH_INCHES = 8.5
    HEIGHT_INCHES = 11
    WIDTH_PIXELS = int(WIDTH_INCHES * DPI)
    HEIGHT_PIXELS = int(HEIGHT_INCHES * DPI)
    
    MARGIN_TOP_INCHES = 0.3
    MARGIN_RIGHT_INCHES = 0.3
    MARGIN_BOTTOM_INCHES = 0.3
    MARGIN_LEFT_INCHES = 0.3
    MARGIN_TOP_PIXELS = int(MARGIN_TOP_INCHES * DPI)
    MARGIN_RIGHT_PIXELS = int(MARGIN_RIGHT_INCHES * DPI)
    MARGIN_BOTTOM_PIXELS = int(MARGIN_BOTTOM_INCHES * DPI)
    MARGIN_LEFT_PIXELS = int(MARGIN_LEFT_INCHES * DPI)
    
    FONT_PATH = "assets/fonts/Dekko-Regular.ttf"
    INSTRUCTIONS_PATH = "assets/how to play/How To Play.pdf"
    OUTPUT_PATH = "output/GameRules_CallingCards_Tokens.pdf"

class BingoCardLayout:
    CARD_AMOUNT = 50
    NUM_PDFS = 2

    FRAME_ENABLED = True
    FRAME_PADDING_TOP_INCHES = 0.317
    FRAME_PADDING_RIGHT_INCHES = 0.333
    FRAME_PADDING_BOTTOM_INCHES = 0.533
    FRAME_PADDING_LEFT_INCHES = 0.333
    FRAME_PADDING_TOP_PIXELS = int(FRAME_PADDING_TOP_INCHES * PageLayout.DPI)
    FRAME_PADDING_RIGHT_PIXELS = int(FRAME_PADDING_RIGHT_INCHES * PageLayout.DPI)
    FRAME_PADDING_BOTTOM_PIXELS = int(FRAME_PADDING_BOTTOM_INCHES * PageLayout.DPI)
    FRAME_PADDING_LEFT_PIXELS = int(FRAME_PADDING_LEFT_INCHES * PageLayout.DPI)

    GRID_COLS = 5
    GRID_ROWS = 5
    GRID_MARGIN_TOP_INCHES = 0.1
    GRID_MARGIN_TOP_PIXELS = int(GRID_MARGIN_TOP_INCHES * PageLayout.DPI)
    GRID_LINE_COLOR = "#69622c"
    GRID_LINE_THICKNESS_INCHES = 0.023
    GRID_LINE_THICKNESS_PIXELS = int(GRID_LINE_THICKNESS_INCHES * PageLayout.DPI)

    CELL_PADDING_X_RATIO = 0.1
    CELL_PADDING_Y_RATIO = 0.05

    LABEL_COLOR = "#581a4d"
    LABEL_HEIGHT_RATIO = 0.14
    LABEL_GAP_RATIO = 0.3
    LABEL_FONT_SCALE = 1.0

    BINGO_IMAGES_PATH = "assets/bingo images"
    HEADER_IMAGE_PATH = "assets/header/Bingo_Card_Header.png"
    FRAME_IMAGE_PATH = "assets/frame/Halloween_Border.png"
    FREE_SPACE_IMAGE_PATH = "assets/free space/Free_Space.png"
    OUTPUT_PATH = "output/Bingo_Cards.pdf"

class BingoCardMultiLayout:
    CARD_AMOUNT = 50
    NUM_PDFS = 2

    FRAME_ENABLED = True
    FRAME_PADDING_TOP_INCHES = 0.317
    FRAME_PADDING_RIGHT_INCHES = 0.333
    FRAME_PADDING_BOTTOM_INCHES = 0.533
    FRAME_PADDING_LEFT_INCHES = 0.333
    FRAME_PADDING_TOP_PIXELS = int(FRAME_PADDING_TOP_INCHES * PageLayout.DPI)
    FRAME_PADDING_RIGHT_PIXELS = int(FRAME_PADDING_RIGHT_INCHES * PageLayout.DPI)
    FRAME_PADDING_BOTTOM_PIXELS = int(FRAME_PADDING_BOTTOM_INCHES * PageLayout.DPI)
    FRAME_PADDING_LEFT_PIXELS = int(FRAME_PADDING_LEFT_INCHES * PageLayout.DPI)

    HEADER_MARGIN_BOTTOM_INCHES = 0.1
    HEADER_MARGIN_BOTTOM_PIXELS = int(HEADER_MARGIN_BOTTOM_INCHES * PageLayout.DPI)

    GRID_COLS = 5
    GRID_ROWS = 5
    GRID_LINE_COLOR = "#69622c"
    GRID_LINE_THICKNESS_INCHES = 0.023
    GRID_LINE_THICKNESS_PIXELS = int(GRID_LINE_THICKNESS_INCHES * PageLayout.DPI)

    CELL_PADDING_X_RATIO = 0.1
    CELL_PADDING_Y_RATIO = 0.05

    LABEL_COLOR = "#581a4d"
    LABEL_HEIGHT_RATIO = 0.14
    LABEL_GAP_RATIO = 0.3
    LABEL_FONT_SCALE = 1.0

    BINGO_IMAGES_PATH = "assets/bingo images"
    HEADER_IMAGE_PATH = "assets/header/Bingo_Card_Header.png"
    FRAME_IMAGE_PATH = "assets/frame/Halloween_Border.png"
    FREE_SPACE_IMAGE_PATH = "assets/free space/Free_Space.png"
    OUTPUT_PATH = "output/Bingo_Cards_2_per_page.pdf"

class CallingCardsSinglePageLayout:
    GRID_COLS = 5
    GRID_ROWS = 6

    GRID_LINE_COLOR = "#545454"
    GRID_LINE_THICKNESS_INCHES = 0.007
    GRID_LINE_THICKNESS_PIXELS = int(GRID_LINE_THICKNESS_INCHES * PageLayout.DPI)

    CELL_PADDING_X_RATIO = 0.1
    CELL_PADDING_Y_RATIO = 0.05

    LABEL_COLOR = "#581a4d"
    LABEL_HEIGHT_RATIO = 0.14
    LABEL_GAP_RATIO = 0.3
    LABEL_FONT_SCALE = 1.0

    BINGO_IMAGES_PATH = "assets/Bingo Images"
    HEADER_IMAGE_PATH = "assets/header/Calling_Card_Header.png"
    OUTPUT_PATH = "output/Calling_Cards.pdf"

class CallingCardsMultiPageLayout:
    GRID_COLS = 2
    GRID_ROWS = 2

    GRID_LINE_COLOR = "#69622c"
    GRID_LINE_THICKNESS_INCHES = 0.007
    GRID_LINE_THICKNESS_PIXELS = int(GRID_LINE_THICKNESS_INCHES * PageLayout.DPI)

    CELL_PADDING_X_RATIO = 0.1
    CELL_PADDING_Y_RATIO = 0.05

    LABEL_COLOR = "#581a4d"
    LABEL_HEIGHT_RATIO = 0.14
    LABEL_GAP_RATIO = 0.3
    LABEL_FONT_SCALE = 1.0

    SCISSORS_WIDTH_SCALE_FACTOR = 0.15625
    SCISSORS_HEIGHT_SCALE_FACTOR = 0.07142857142857142857142857142857
    SCISSORS_BOTTOM_MARGIN = 50

    BINGO_IMAGES_PATH = "assets/Bingo Images"
    SCISSORS_IMAGE_PATH = "assets/scissors/scissors.png"
    OUTPUT_PATH = "output/Calling_Cards_Multi.pdf"

class TokensLayout:
    GRID_COLS = 9
    GRID_ROWS = 9

    GRID_LINE_COLOR = "#545454"
    GRID_LINE_THICKNESS = 2

    CELL_PADDING_X_RATIO = 0.1
    CELL_PADDING_Y_RATIO = 0.05

    TOKEN_SCALE_FACTOR = 0

    SCISSORS_WIDTH_SCALE_FACTOR = 0.15625
    SCISSORS_HEIGHT_SCALE_FACTOR = 0.07142857142857142857142857142857
    SCISSORS_BOTTOM_MARGIN = 50

    TOKEN_IMAGE_PATH = "assets/Bingo Token/bingotoken.png"
    SCISSORS_IMAGE_PATH = "assets/scissors/Scissors.png"
    OUTPUT_PATH = "output/Tokens.pdf"
